# Generated by Django 5.2.14 on 2026-05-20 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcm_django", "0009_alter_fcmdevice_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="fcmdevice",
            name="registration_id",
            field=models.TextField(unique=True, verbose_name="Registration token"),
        ),
        migrations.AddIndex(
            model_name="fcmdevice",
            index=models.Index(
                fields=["registration_id", "user"],
                name="fcm_django__registr_dacdb2_idx",
            ),
        ),
    ]
