# Generated by Django 4.0.7 on 2023-08-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='value',
            field=models.TextField(default=''),
        ),
    ]
