# Generated by Django 5.0.6 on 2024-06-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_changelog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changelog",
            name="instance_id",
            field=models.CharField(max_length=255, verbose_name="Instance ID"),
        ),
    ]
