# Generated by Django 5.0.6 on 2024-06-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_alter_changelog_instance_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changelog",
            name="user",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="User"
            ),
        ),
    ]
