# Generated by Django 5.0.6 on 2024-06-17 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_alter_changelog_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChangeLog",
        ),
    ]
