# Generated by Django 3.2.25 on 2025-07-23 15:11

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acls',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('group', models.TextField(blank=True, null=True)),
                ('cache_key', models.TextField(blank=True, null=True, unique=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
            ],
            options={
                'db_table': 'acls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AcmeStorage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.TextField(blank=True, null=True, unique=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('ttl', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'acme_storage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BasicauthCredentials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('username', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
            ],
            options={
                'db_table': 'basicauth_credentials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CaCertificates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('cert', models.TextField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('cert_digest', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'ca_certificates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('cert', models.TextField(blank=True, null=True)),
                ('key', models.TextField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('cert_alt', models.TextField(blank=True, null=True)),
                ('key_alt', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'certificates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClusterEvents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.UUIDField()),
                ('at', models.DateTimeField()),
                ('nbf', models.DateTimeField(blank=True, null=True)),
                ('expire_at', models.DateTimeField()),
                ('channel', models.TextField(blank=True, null=True)),
                ('data', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cluster_events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClusteringDataPlanes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.TextField()),
                ('ip', models.TextField()),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('config_hash', models.TextField()),
                ('ttl', models.DateTimeField(blank=True, null=True)),
                ('version', models.TextField(blank=True, null=True)),
                ('sync_status', models.TextField()),
            ],
            options={
                'db_table': 'clustering_data_planes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consumers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('username', models.TextField(blank=True, null=True)),
                ('custom_id', models.TextField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
            ],
            options={
                'db_table': 'consumers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HmacauthCredentials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('username', models.TextField(blank=True, null=True)),
                ('secret', models.TextField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
            ],
            options={
                'db_table': 'hmacauth_credentials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JwtSecrets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('key', models.TextField(blank=True, null=True)),
                ('secret', models.TextField(blank=True, null=True)),
                ('algorithm', models.TextField(blank=True, null=True)),
                ('rsa_public_key', models.TextField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
            ],
            options={
                'db_table': 'jwt_secrets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeyauthCredentials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('key', models.TextField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('ttl', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'keyauth_credentials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Locks',
            fields=[
                ('key', models.TextField(primary_key=True, serialize=False)),
                ('owner', models.TextField(blank=True, null=True)),
                ('ttl', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'locks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oauth2AuthorizationCodes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('authenticated_userid', models.TextField(blank=True, null=True)),
                ('scope', models.TextField(blank=True, null=True)),
                ('ttl', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.TextField(blank=True, null=True)),
                ('challenge_method', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oauth2_authorization_codes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oauth2Credentials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('client_id', models.TextField(blank=True, null=True)),
                ('client_secret', models.TextField(blank=True, null=True)),
                ('redirect_uris', models.TextField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('client_type', models.TextField(blank=True, null=True)),
                ('hash_secret', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oauth2_credentials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oauth2Tokens',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_type', models.TextField(blank=True, null=True)),
                ('expires_in', models.IntegerField(blank=True, null=True)),
                ('authenticated_userid', models.TextField(blank=True, null=True)),
                ('scope', models.TextField(blank=True, null=True)),
                ('ttl', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oauth2_tokens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('key', models.TextField(primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'parameters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plugins',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.TextField()),
                ('config', models.JSONField()),
                ('enabled', models.BooleanField(default=True)),
                ('cache_key', models.TextField(blank=True, null=True, unique=True)),
                ('protocols', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=['grpc', 'grpcs', 'http', 'https'], null=True, size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
            ],
            options={
                'db_table': 'plugins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RatelimitingMetrics',
            fields=[
                ('identifier', models.TextField(primary_key=True, serialize=False)),
                ('period', models.TextField()),
                ('period_date', models.DateTimeField()),
                ('service_id', models.UUIDField()),
                ('route_id', models.UUIDField()),
                ('value', models.IntegerField(blank=True, null=True)),
                ('ttl', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ratelimiting_metrics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResponseRatelimitingMetrics',
            fields=[
                ('identifier', models.TextField(primary_key=True, serialize=False)),
                ('period', models.TextField()),
                ('period_date', models.DateTimeField()),
                ('service_id', models.UUIDField()),
                ('route_id', models.UUIDField()),
                ('value', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'response_ratelimiting_metrics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('protocols', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('methods', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('hosts', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('paths', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('snis', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('sources', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=None)),
                ('destinations', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=None)),
                ('regex_priority', models.BigIntegerField(blank=True, default=0, null=True)),
                ('strip_path', models.BooleanField(blank=True, default=True, null=True)),
                ('preserve_host', models.BooleanField(blank=True, default=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('https_redirect_status_code', models.IntegerField(blank=True, null=True)),
                ('headers', models.JSONField(blank=True, null=True)),
                ('path_handling', models.TextField(blank=True, default='v0', null=True)),
                ('request_buffering', models.BooleanField(blank=True, default=True, null=True)),
                ('response_buffering', models.BooleanField(blank=True, default=True, null=True)),
                ('expression', models.TextField(default='')),
                ('priority', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'routes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchemaMeta',
            fields=[
                ('key', models.TextField(primary_key=True, serialize=False)),
                ('subsystem', models.TextField()),
                ('last_executed', models.TextField(blank=True, null=True)),
                ('executed', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('pending', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
            ],
            options={
                'db_table': 'schema_meta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('retries', models.BigIntegerField(blank=True, default=5, null=True)),
                ('protocol', models.TextField(blank=True, null=True)),
                ('host', models.TextField(blank=True, null=True)),
                ('port', models.BigIntegerField(blank=True, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('connect_timeout', models.BigIntegerField(blank=True, default=8000, null=True)),
                ('write_timeout', models.BigIntegerField(blank=True, default=8000, null=True)),
                ('read_timeout', models.BigIntegerField(blank=True, default=8000, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('tls_verify', models.BooleanField(blank=True, null=True)),
                ('tls_verify_depth', models.SmallIntegerField(blank=True, null=True)),
                ('ca_certificates', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, null=True, size=None)),
                ('enabled', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'db_table': 'services',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.TextField(blank=True, null=True, unique=True)),
                ('expires', models.IntegerField(blank=True, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('ttl', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sessions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Snis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.TextField(unique=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
            ],
            options={
                'db_table': 'snis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('entity_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_name', models.TextField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
            ],
            options={
                'db_table': 'tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Targets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('target', models.TextField()),
                ('weight', models.IntegerField(default=100)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
            ],
            options={
                'db_table': 'targets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ttls',
            fields=[
                ('primary_key_value', models.TextField(primary_key=True, serialize=False)),
                ('primary_uuid_value', models.UUIDField(blank=True, null=True)),
                ('table_name', models.TextField()),
                ('primary_key_name', models.TextField()),
                ('expire_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ttls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Upstreams',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('hash_on', models.TextField(blank=True, default=None, null=True)),
                ('hash_fallback', models.TextField(blank=True, default=None, null=True)),
                ('hash_on_header', models.TextField(blank=True, null=True)),
                ('hash_fallback_header', models.TextField(blank=True, null=True)),
                ('hash_on_cookie', models.TextField(blank=True, null=True)),
                ('hash_on_cookie_path', models.TextField(blank=True, default='/', null=True)),
                ('slots', models.IntegerField(default=10000)),
                ('healthchecks', models.JSONField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('algorithm', models.TextField(blank=True, null=True)),
                ('host_header', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'upstreams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VaultsBeta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('prefix', models.TextField(blank=True, null=True, unique=True)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('config', models.JSONField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
            ],
            options={
                'db_table': 'vaults_beta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Workspaces',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True, unique=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workspaces',
                'managed': False,
            },
        ),
    ]
