# Generated by Django 3.1.13 on 2022-12-01 14:28

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KongEntityMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, null=True)),
                ('entity_id', models.UUIDField(default=uuid.uuid4)),
                ('entity_type', models.IntegerField(choices=[(1, 'Route'), (2, 'Service'), (3, 'Upstream')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'metadatas',
                'managed': False,
            },
        )
    ]
